name: MOSIP-SDK NPM Publish

on:
  release:
    types: [ published ]
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for NPM Publish'
        type: string
  push:
    branches:
      - release*
      - master
      - develop*
      - MOSIP*

jobs:
  publish-to-npm-registry:
    name: Publish ${{ matrix.service.name }}
    strategy:
      matrix:
        service:
          - name: json-form-builder
            path: './json-form-builder'
          - name: react-secure-biometric-interface-integrator
            path: './react-secure-biometric-interface-integrator'
          - name: secure-biometric-interface-integrator
            path: './secure-biometric-interface-integrator'
          - name: react-sign-in-with-esignet
            path: './react-sign-in-with-esignet'
          - name: sign-in-with-esignet
            path: './sign-in-with-esignet'
    if: "${{ !contains(github.ref, 'master') && github.event_name != 'pull_request' && github.event_name == 'workflow_dispatch' }}"
    uses: mosip/kattu/.github/workflows/npm-publish-to-npm-registry.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.service.path }}
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}